import js from '@eslint/js';
import { defineConfig } from 'eslint/config';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

export default defineConfig(
  {
    // Generated by scripts/compile-schema.mjs; never hand-edited or held to our lint rules.
    ignores: [
      'dist/',
      'coverage/',
      'node_modules/',
      'samples/',
      'src/core/envelope/schema/generated/',
    ],
  },
  js.configs.recommended,
  ts.configs.strict,
  svelte.configs.recommended,
  {
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
  },
  {
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
        extraFileExtensions: ['.svelte'],
        svelteConfig,
      },
    },
  },
  {
    // The service worker template runs in a ServiceWorkerGlobalScope, not a window.
    files: ['scripts/sw.template.js'],
    languageOptions: {
      globals: { ...globals.serviceworker, ...globals.browser },
    },
    rules: { 'no-console': 'error' },
  },
  {
    files: ['src/**/*.ts', 'src/**/*.svelte'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['node:*', 'fs', 'path', 'crypto', 'os'],
              message: 'src/ is browser code; Node APIs are allowed only in tests.',
            },
          ],
        },
      ],
      'no-console': 'error',
    },
  },
);
