import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { describe, expect, it } from 'vitest';
import { ROOT } from '../helpers';

const SRC = join(ROOT, 'src');
/** Generated by scripts/compile-schema.mjs; not hand-written application code. */
const SKIP_DIRS = new Set(['generated']);

/** Removes comments so prose that merely mentions the word is not flagged. Deliberately simple:
 * over-stripping can only hide a use, and the self-tests below pin the cases that matter. */
function stripComments(source: string): string {
  return source
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:'"`])\/\/.*$/gm, '$1');
}

/** Any reference to the `console` global: calls, bracket access, destructuring or aliasing. */
export function findConsoleUses(source: string): string[] {
  return stripComments(source).match(/\bconsole\b/g) ?? [];
}

function listSource(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) {
      if (!SKIP_DIRS.has(name)) out.push(...listSource(path));
    } else if (/\.(ts|js|mjs|svelte)$/.test(name) && !name.endsWith('.d.ts')) {
      out.push(path);
    }
  }
  return out;
}

describe('production source never logs to the console', () => {
  it('scans a non-trivial set of source files', () => {
    expect(listSource(SRC).length).toBeGreaterThan(40);
  });

  it('src/ contains no reference to console (privacy: logs must carry no CSV values or filenames)', () => {
    const offenders = listSource(SRC)
      .filter((file) => findConsoleUses(readFileSync(file, 'utf8')).length > 0)
      .map((file) => relative(ROOT, file).split(sep).join('/'));
    expect(offenders).toEqual([]);
  });
});

describe('findConsoleUses detector', () => {
  it.each([
    'console.log(row)',
    'console.error("x")',
    'console["warn"](x)',
    'const c = console;',
    'const { log } = console;',
    '<script>\n  console.debug(x);\n</script>',
  ])('flags %j', (source) => {
    expect(findConsoleUses(source).length).toBeGreaterThan(0);
  });

  it.each([
    '// console.log(x) is forbidden here',
    '/* console.log(x) */',
    '<!-- console.log(x) -->',
    'const consoleWidth = 80;',
    'const reconsole = 1;',
  ])('ignores %j', (source) => {
    expect(findConsoleUses(source)).toEqual([]);
  });
});
