import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { parse } from 'svelte/compiler';
import ts from 'typescript';
import { describe, expect, it } from 'vitest';
import { ROOT } from '../helpers';

const SRC = join(ROOT, 'src');
/** Generated by scripts/compile-schema.mjs; not hand-written application code. */
const SKIP_DIRS = new Set(['generated']);

type SourceKind = 'ts' | 'js' | 'svelte';

function countInTypeScript(source: string, kind: 'ts' | 'js'): number {
  const file = ts.createSourceFile(
    kind === 'ts' ? 'file.ts' : 'file.js',
    source,
    ts.ScriptTarget.Latest,
    true,
    kind === 'ts' ? ts.ScriptKind.TS : ts.ScriptKind.JS,
  );
  let count = 0;
  const visit = (node: ts.Node): void => {
    if (ts.isIdentifier(node) && node.text === 'console') count += 1;
    // globalThis['console'] and similar string-keyed access
    if (
      ts.isElementAccessExpression(node) &&
      ts.isStringLiteralLike(node.argumentExpression) &&
      node.argumentExpression.text === 'console'
    ) {
      count += 1;
    }
    ts.forEachChild(node, visit);
  };
  visit(file);
  return count;
}

/** Counts `console` identifiers anywhere in a parsed Svelte AST (script, template expressions and
 * event handlers). Comments, text nodes and string literals are never Identifier nodes. */
function countInSvelte(source: string): number {
  const root: unknown = parse(source, { modern: true });
  const seen = new WeakSet<object>();
  let count = 0;
  const visit = (value: unknown): void => {
    if (typeof value !== 'object' || value === null || seen.has(value)) return;
    seen.add(value);
    const node = value as { type?: unknown; name?: unknown };
    if (node.type === 'Identifier' && node.name === 'console') count += 1;
    for (const child of Object.values(value)) visit(child);
  };
  visit(root);
  return count;
}

/**
 * Syntax-aware detection of the `console` global: real parsing (TypeScript's parser for
 * .ts/.js, Svelte's compiler for .svelte), so comments and string/regex/template contents can
 * neither hide a use nor cause a false positive. Flags calls, bracket access, aliasing,
 * destructuring and `window.console`. Parse failures throw, failing the test loudly rather than
 * silently skipping a file.
 */
export function findConsoleUses(source: string, kind: SourceKind): string[] {
  const count = kind === 'svelte' ? countInSvelte(source) : countInTypeScript(source, kind);
  return Array.from({ length: count }, () => 'console');
}

function kindOf(file: string): SourceKind {
  if (file.endsWith('.svelte')) return 'svelte';
  return file.endsWith('.ts') ? 'ts' : 'js';
}

function listSource(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) {
      if (!SKIP_DIRS.has(name)) out.push(...listSource(path));
    } else if (/\.(ts|js|mjs|svelte)$/.test(name) && !name.endsWith('.d.ts')) {
      out.push(path);
    }
  }
  return out;
}

describe('production source never logs to the console', () => {
  it('scans a non-trivial set of source files', () => {
    expect(listSource(SRC).length).toBeGreaterThan(40);
  });

  it('src/ contains no reference to console (privacy: logs must carry no CSV values or filenames)', () => {
    const offenders = listSource(SRC)
      .filter((file) => findConsoleUses(readFileSync(file, 'utf8'), kindOf(file)).length > 0)
      .map((file) => relative(ROOT, file).split(sep).join('/'));
    expect(offenders).toEqual([]);
  });
});

describe('findConsoleUses detector', () => {
  it.each([
    ['ts', 'console.log(row)'],
    ['ts', 'console.error("x")'],
    ['ts', 'console["warn"](x)'],
    ['ts', 'const c = console;'],
    ['ts', 'const { log } = console;'],
    ['ts', 'window.console.log(x)'],
    ['ts', 'const f = `${console.log(x)}`;'],
    ['svelte', '<script>\n  console.debug(x);\n</script>'],
    ['svelte', '<button onclick={() => console.log(1)}>x</button>'],
    ['svelte', '<p>{console.log(1)}</p>'],
    // Reviewed blind spots (PR #7): a "/*" inside a string must not open a comment...
    ['ts', 'const g = "src/*";\nconsole.log(1);\n/* note */'],
    // ...and an escaped "//" inside a regex literal must not start a line comment.
    ['ts', String.raw`const r = /a\/\//; console.log(1)`],
    // CodeQL alert #1: "<!--" / "-->" inside strings must not hide code between them.
    ['svelte', '<script>\n  const a = "<!--";\n  console.log(a);\n  const b = "-->";\n</script>'],
    ['ts', 'const a = "<!--"; console.log(a); const b = "-->";'],
    ['ts', 'const s = "http://x"; console.log(s)'],
  ] as const)('flags (%s) %j', (kind, source) => {
    expect(findConsoleUses(source, kind).length).toBeGreaterThan(0);
  });

  it.each([
    ['ts', '// console.log(x) is forbidden here'],
    ['ts', '/* console.log(x) */'],
    ['ts', '/**\n * console.log(x)\n */\nexport const a = 1;'],
    ['ts', 'const consoleWidth = 80;'],
    ['ts', 'const reconsole = 1;'],
    ['ts', 'const s = "the console is not used";'],
    ['ts', "const s = 'console.log(1)';"],
    ['svelte', '<!-- console.log(x) -->'],
    ['svelte', '<p>console output is disabled</p>'],
    ['svelte', '<script>\n  // console.log(x)\n  const a = 1;\n</script>'],
  ] as const)('ignores (%s) %j', (kind, source) => {
    expect(findConsoleUses(source, kind)).toEqual([]);
  });
});
